development:
  host: localhost
  database: sc2rank_development

test:
  host: localhost
  database: sc2rank_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
